simulate = false
can_port = "can0"

[joint_1]
can_id = 0x01
master_id = 0x11
offset = 0.0
dir = -1.0
mit_pid = { kp = 0.0, kd = 0.5 }

[joint_2]
can_id = 0x02
master_id = 0x12
offset = 0.0
dir = -1.0
mit_pid = { kp = 0.0, kd = 0.5 }

[joint_3]
can_id = 0x03
master_id = 0x13
offset = 0.0
dir = 1.0
mit_pid = { kp = 0.0, kd = 0.5 }

[joint_4]
id = 7
offset = 0.0
dir = 1.0
mit_pid = { kp = 80.0, kd = 0.5 }

[joint_5]
can_id = 0x05
master_id = 0x15
offset = 0.0
dir = 1.0
mit_pid = { kp = 0.0, kd = 0.5 }

[joint_6]
id = 7
offset = 0.0
dir = 1.0
mit_pid = { kp = 80.0, kd = 0.5 }
